[package]
name = "kallip-daemon-client"
description = "UDS client library for the kallip local daemon"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
kallip-daemon-common = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net"] }
